import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Analytics | NextJS App",
  description: "Generated by me",
};


const page = () => {
  return (
    <div>analytics</div>
  )
}

export default page