import { Metadata } from "next";
import Link from "next/link"
import React from 'react'

export const metadata: Metadata = {
  title: "Users | NextJS App",
  description: "Generated by me",
};

const page = () => {
  return (
    <div>
        <h1>Dashboard Users</h1>

        <ul className="mt-10">
            <li><Link href="/dashboard/users/0">User 0</Link></li>
            <li><Link href="/dashboard/users/1">User 1</Link></li>
            <li><Link href="/dashboard/users/2">User 2</Link></li>
            <li><Link href="/dashboard/users/3">User 3</Link></li>

        </ul>
    </div>
  )
}

export default page